### ISSUE TITLE
Variable '_default' implicitly has an 'any' type

### ISSUE THREAD

**Issue by valentinpalkovic** [hinok/react-router-last-location#28] opened 2019-07-05 08:42 UTC
Following error occurs after updating to the current 2.0.0 version during `tsc --noEmit`. The project uses the current create-react-app package:

```
node_modules/react-router-last-location/dist/LastLocationProvider.d.ts:10:15 - error TS7005: Variable '_default' implicitly has an 'any' type.
  declare const _default;
```

**Comment by hinok** [comment] 2019-07-05 09:56
Hey @valentinpalkovic ,
Could you create an example repository?
I cannot reproduce it using the newest CRA and 2.0.0.

**Comment by hinok** [comment] 2019-07-05 10:03
I created repository with `CRA` and `react-router-last-location` and it works correctly:
https://github.com/hinok/create-react-app-react-router-last-location

Could you check if you have that problem in the linked repo above?

**Comment by hinok** [comment] 2019-07-07 12:59
@valentinpalkovic  Try `2.0.1`, the problem should be solved.

**Comment by hinok** [comment] 2019-07-07 15:04
Because #29 and this issue are related, and [I can easily see that typings for `_default` are provided](https://unpkg.com/react-router-last-location@2.0.1/dist/LastLocationProvider.d.ts) in `2.0.1`, I close this issue.

**Closed by hinok** 2019-07-07 15:04 UTC
